export type User = {
    id: string;
    name: string;
    email: string;
    grade: string;
    school: string;
    level: number;
    experience: number;
    nextLevelExp: number;
};

export type Material = {
    id: string;
    title: string;
    description: string;
    content: string;
    category: string;
    subject: string;
    duration: number;
    difficulty: 'Pemula' | 'Menengah' | 'Lanjutan';
    tags: string[];
    publishedDate: Date;
    author: string;
    views: number;
    likes: number;
    isBookmarked?: boolean;
};

export type Category = {
    id: string;
    name: string;
    icon: string;
    count: number;
};

export type LearningProgress = {
    id: string;
    materialId: string;
    materialTitle: string;
    category: string;
    progress: number;
    lastAccessed: Date;
    timeSpent: number;
    completed: boolean;
    quizScore?: number;
    completionDate?: Date;
};

export type StudyStatistic = {
    totalStudyTime: number;
    materialsCompleted: number;
    averageQuizScore: number;
    consecutiveDays: number;
    totalPoints: number;
    rank: number;
    percentile: number;
};

export const mockUser: User = {
    id: 'user-123',
    name: 'Handika',
    email: 'handika@example.com',
    grade: '12 IPA',
    school: 'SMA Negeri 1 Jakarta',
    level: 7,
    experience: 1250,
    nextLevelExp: 1500,
};

export const learningProgress: LearningProgress[] = [
    {
        id: 'prog-1',
        materialId: 'mat-1',
        materialTitle: 'Trigonometri Dasar untuk Ujian Nasional',
        category: 'Matematika',
        progress: 100,
        lastAccessed: new Date('2023-11-20'),
        timeSpent: 120,
        completed: true,
        quizScore: 85,
        completionDate: new Date('2023-11-20'),
    },
    {
        id: 'prog-2',
        materialId: 'mat-2',
        materialTitle: 'Hukum Newton dan Aplikasinya',
        category: 'Fisika',
        progress: 75,
        lastAccessed: new Date('2023-11-22'),
        timeSpent: 90,
        completed: false,
        quizScore: 78,
    },
    {
        id: 'prog-3',
        materialId: 'mat-3',
        materialTitle: 'Struktur Atom dan Sistem Periodik',
        category: 'Kimia',
        progress: 100,
        lastAccessed: new Date('2023-11-18'),
        timeSpent: 110,
        completed: true,
        quizScore: 92,
        completionDate: new Date('2023-11-18'),
    },
    {
        id: 'prog-4',
        materialId: 'mat-4',
        materialTitle: 'Sel Hewan dan Sel Tumbuhan: Perbedaan dan Persamaan',
        category: 'Biologi',
        progress: 45,
        lastAccessed: new Date('2023-11-21'),
        timeSpent: 60,
        completed: false,
    },
    {
        id: 'prog-5',
        materialId: 'mat-5',
        materialTitle: 'Pembahasan Soal UN Bahasa Indonesia 2023',
        category: 'Bahasa Indonesia',
        progress: 100,
        lastAccessed: new Date('2023-11-19'),
        timeSpent: 95,
        completed: true,
        quizScore: 88,
        completionDate: new Date('2023-11-19'),
    },
    {
        id: 'prog-6',
        materialId: 'mat-6',
        materialTitle: 'English Tenses Mastery for Final Exam',
        category: 'Bahasa Inggris',
        progress: 30,
        lastAccessed: new Date('2023-11-23'),
        timeSpent: 45,
        completed: false,
    },
];

export const studyStatistics: StudyStatistic = {
    totalStudyTime: 520,
    materialsCompleted: 3,
    averageQuizScore: 85,
    consecutiveDays: 14,
    totalPoints: 1250,
    rank: 45,
    percentile: 85,
};


export const categories: Category[] = [
    { id: 'cat-1', name: 'Matematika', icon: '📐', count: 11 },
    { id: 'cat-2', name: 'Fisika', icon: '⚛️', count: 9 },
    { id: 'cat-3', name: 'Kimia', icon: '🧪', count: 7 },
    { id: 'cat-4', name: 'Biologi', icon: '🧬', count: 10 },
    { id: 'cat-5', name: 'Bahasa Indonesia', icon: '📖', count: 11 },
    { id: 'cat-6', name: 'Bahasa Inggris', icon: '🔤', count: 6 },
    { id: 'cat-7', name: 'Sejarah', icon: '📜', count: 6 },
    { id: 'cat-8', name: 'Geografi', icon: '🌍', count: 12 },
];

export const materials: Material[] = [
    {
        id: 'mat-1',
        title: 'Trigonometri Dasar untuk Ujian Nasional',
        description: 'Pelajari konsep dasar trigonometri, identitas, dan aplikasinya dalam soal ujian',
        content: `
# Trigonometri Dasar

## Pengertian Trigonometri
Trigonometri adalah cabang matematika yang mempelajari hubungan antara sudut dan sisi segitiga.

## Identitas Trigonometri Penting
1. sin²θ + cos²θ = 1
2. 1 + tan²θ = sec²θ
3. 1 + cot²θ = csc²θ

## Contoh Soal
Sebuah segitiga siku-siku memiliki sisi depan 3 cm dan sisi miring 5 cm. Tentukan nilai sin θ!

### Penyelesaian
sin θ = sisi depan / sisi miring = 3/5 = 0.6

## Latihan Soal
1. Diketahui cos θ = 4/5, tentukan nilai sin θ!
2. Hitung nilai dari sin 30° + cos 60°!
    `,
        category: 'Matematika',
        subject: 'Trigonometri',
        duration: 45,
        difficulty: 'Pemula',
        tags: ['Trigonometri', 'Segitiga', 'Sudut', 'Dasar'],
        publishedDate: new Date('2023-10-15'),
        author: 'Budi Santoso, S.Pd.',
        views: 1245,
        likes: 89,
        isBookmarked: true,
    },
    {
        id: 'mat-2',
        title: 'Aljabar Linear: Matriks dan Determinan',
        description: 'Konsep dasar matriks, operasi matriks, dan determinan',
        content: 'Konten tentang aljabar linear...',
        category: 'Matematika',
        subject: 'Aljabar',
        duration: 60,
        difficulty: 'Menengah',
        tags: ['Matriks', 'Determinan', 'Aljabar'],
        publishedDate: new Date('2023-10-12'),
        author: 'Prof. Ahmad, M.Sc.',
        views: 987,
        likes: 67,
        isBookmarked: false,
    },
    {
        id: 'mat-3',
        title: 'Kalkulus Diferensial',
        description: 'Pengertian turunan dan aplikasinya dalam masalah nyata',
        content: 'Konten tentang kalkulus diferensial...',
        category: 'Matematika',
        subject: 'Kalkulus',
        duration: 90,
        difficulty: 'Lanjutan',
        tags: ['Turunan', 'Limit', 'Kalkulus'],
        publishedDate: new Date('2023-10-10'),
        author: 'Dr. Sari, Ph.D.',
        views: 1567,
        likes: 134,
        isBookmarked: true,
    },
    {
        id: 'mat-4',
        title: 'Geometri Ruang',
        description: 'Materi tentang bangun ruang tiga dimensi',
        content: 'Konten tentang geometri ruang...',
        category: 'Matematika',
        subject: 'Geometri',
        duration: 50,
        difficulty: 'Menengah',
        tags: ['Bangun Ruang', 'Volume', 'Luas'],
        publishedDate: new Date('2023-10-08'),
        author: 'Rina, S.Pd.',
        views: 845,
        likes: 45,
        isBookmarked: false,
    },
    {
        id: 'mat-5',
        title: 'Statistika dan Probabilitas',
        description: 'Dasar-dasar statistika dan konsep probabilitas',
        content: 'Konten tentang statistika...',
        category: 'Matematika',
        subject: 'Statistika',
        duration: 70,
        difficulty: 'Menengah',
        tags: ['Mean', 'Median', 'Probabilitas'],
        publishedDate: new Date('2023-10-05'),
        author: 'Dr. Andi, M.Si.',
        views: 1123,
        likes: 78,
        isBookmarked: true,
    },
    {
        id: 'mat-6',
        title: 'Persamaan Kuadrat',
        description: 'Menyelesaikan persamaan kuadrat dengan berbagai metode',
        content: 'Konten tentang persamaan kuadrat...',
        category: 'Matematika',
        subject: 'Aljabar',
        duration: 40,
        difficulty: 'Pemula',
        tags: ['Kuadrat', 'Akar', 'Diskriminan'],
        publishedDate: new Date('2023-10-03'),
        author: 'Budi Santoso, S.Pd.',
        views: 734,
        likes: 56,
        isBookmarked: false,
    },
    {
        id: 'mat-7',
        title: 'Integral dan Aplikasinya',
        description: 'Konsep integral tentu dan tak tentu',
        content: 'Konten tentang integral...',
        category: 'Matematika',
        subject: 'Kalkulus',
        duration: 80,
        difficulty: 'Lanjutan',
        tags: ['Integral', 'Luas', 'Volume'],
        publishedDate: new Date('2023-10-01'),
        author: 'Prof. Ahmad, M.Sc.',
        views: 923,
        likes: 67,
        isBookmarked: true,
    },
    {
        id: 'mat-8',
        title: 'Logika Matematika',
        description: 'Dasar-dasar logika dan pembuktian matematika',
        content: 'Konten tentang logika matematika...',
        category: 'Matematika',
        subject: 'Logika',
        duration: 55,
        difficulty: 'Pemula',
        tags: ['Logika', 'Pembuktian', 'Premis'],
        publishedDate: new Date('2023-09-28'),
        author: 'Dr. Sari, Ph.D.',
        views: 645,
        likes: 43,
        isBookmarked: false,
    },
    {
        id: 'mat-9',
        title: 'Barisan dan Deret',
        description: 'Aritmatika, geometri, dan deret tak hingga',
        content: 'Konten tentang barisan dan deret...',
        category: 'Matematika',
        subject: 'Aljabar',
        duration: 65,
        difficulty: 'Menengah',
        tags: ['Aritmatika', 'Geometri', 'Deret'],
        publishedDate: new Date('2023-09-25'),
        author: 'Rina, S.Pd.',
        views: 856,
        likes: 61,
        isBookmarked: true,
    },
    {
        id: 'mat-10',
        title: 'Fungsi Komposisi dan Invers',
        description: 'Materi tentang fungsi dan operasinya',
        content: 'Konten tentang fungsi...',
        category: 'Matematika',
        subject: 'Aljabar',
        duration: 45,
        difficulty: 'Menengah',
        tags: ['Fungsi', 'Komposisi', 'Invers'],
        publishedDate: new Date('2023-09-22'),
        author: 'Dr. Andi, M.Si.',
        views: 734,
        likes: 52,
        isBookmarked: false,
    },
    {
        id: 'mat-11',
        title: 'Peluang dan Kombinatorik',
        description: 'Permutasi, kombinasi, dan peluang kejadian',
        content: 'Konten tentang peluang...',
        category: 'Matematika',
        subject: 'Statistika',
        duration: 60,
        difficulty: 'Menengah',
        tags: ['Peluang', 'Permutasi', 'Kombinasi'],
        publishedDate: new Date('2023-09-20'),
        author: 'Budi Santoso, S.Pd.',
        views: 912,
        likes: 74,
        isBookmarked: true,
    },

    {
        id: 'fis-1',
        title: 'Hukum Newton dan Aplikasinya',
        description: 'Memahami tiga hukum Newton beserta contoh penerapannya dalam kehidupan sehari-hari',
        content: `
# Hukum Newton

## Hukum I Newton (Hukum Inersia)
"Sebuah benda akan tetap diam atau bergerak lurus beraturan kecuali ada gaya yang bekerja padanya."

## Hukum II Newton
"Percepatan sebuah benda berbanding lurus dengan gaya total yang bekerja padanya dan berbanding terbalik dengan massanya."

## Hukum III Newton (Hukum Aksi-Reaksi)
"Untuk setiap aksi, ada reaksi yang sama besar tetapi berlawanan arah."

## Contoh Penerapan
- Mengapa kita terdorong ke belakang saat bus tiba-tiba berangkat?
- Bagaimana roket bisa meluncur ke angkasa?
    `,
        category: 'Fisika',
        subject: 'Mekanika',
        duration: 60,
        difficulty: 'Menengah',
        tags: ['Hukum Newton', 'Gaya', 'Gerak', 'Dinamika'],
        publishedDate: new Date('2023-10-10'),
        author: 'Dr. Ani Lestari, M.Pd.',
        views: 1876,
        likes: 124,
        isBookmarked: false,
    },
    {
        id: 'fis-2',
        title: 'Listrik dan Magnet',
        description: 'Konsep dasar listrik statis dan magnet',
        content: 'Konten tentang listrik dan magnet...',
        category: 'Fisika',
        subject: 'Elektromagnetik',
        duration: 75,
        difficulty: 'Lanjutan',
        tags: ['Listrik', 'Magnet', 'Medan'],
        publishedDate: new Date('2023-10-08'),
        author: 'Prof. Joko, M.Si.',
        views: 1345,
        likes: 98,
        isBookmarked: true,
    },
    {
        id: 'fis-3',
        title: 'Termodinamika Dasar',
        description: 'Hukum-hukum termodinamika dan aplikasinya',
        content: 'Konten tentang termodinamika...',
        category: 'Fisika',
        subject: 'Termodinamika',
        duration: 80,
        difficulty: 'Menengah',
        tags: ['Termodinamika', 'Kalor', 'Entropi'],
        publishedDate: new Date('2023-10-05'),
        author: 'Dr. Ani Lestari, M.Pd.',
        views: 987,
        likes: 67,
        isBookmarked: false,
    },
    {
        id: 'fis-4',
        title: 'Gelombang dan Optik',
        description: 'Sifat-sifat gelombang dan cahaya',
        content: 'Konten tentang gelombang dan optik...',
        category: 'Fisika',
        subject: 'Optik',
        duration: 70,
        difficulty: 'Menengah',
        tags: ['Gelombang', 'Cahaya', 'Lensa'],
        publishedDate: new Date('2023-10-03'),
        author: 'Prof. Joko, M.Si.',
        views: 1123,
        likes: 89,
        isBookmarked: true,
    },
    {
        id: 'fis-5',
        title: 'Fisika Modern',
        description: 'Relativitas dan mekanika kuantum dasar',
        content: 'Konten tentang fisika modern...',
        category: 'Fisika',
        subject: 'Fisika Modern',
        duration: 90,
        difficulty: 'Lanjutan',
        tags: ['Relativitas', 'Kuantum', 'Atom'],
        publishedDate: new Date('2023-10-01'),
        author: 'Dr. Ani Lestari, M.Pd.',
        views: 856,
        likes: 73,
        isBookmarked: false,
    },
    {
        id: 'fis-6',
        title: 'Kinematika Gerak Lurus',
        description: 'Analisis gerak benda tanpa memperhitungkan penyebab gerak',
        content: 'Konten tentang kinematika...',
        category: 'Fisika',
        subject: 'Mekanika',
        duration: 50,
        difficulty: 'Pemula',
        tags: ['Kinematika', 'Gerak', 'Kecepatan'],
        publishedDate: new Date('2023-09-28'),
        author: 'Prof. Joko, M.Si.',
        views: 1023,
        likes: 81,
        isBookmarked: true,
    },
    {
        id: 'fis-7',
        title: 'Dinamika Rotasi',
        description: 'Gerak rotasi dan momen inersia',
        content: 'Konten tentang dinamika rotasi...',
        category: 'Fisika',
        subject: 'Mekanika',
        duration: 85,
        difficulty: 'Lanjutan',
        tags: ['Rotasi', 'Momen Inersia', 'Torsi'],
        publishedDate: new Date('2023-09-25'),
        author: 'Dr. Ani Lestari, M.Pd.',
        views: 734,
        likes: 56,
        isBookmarked: false,
    },
    {
        id: 'fis-8',
        title: 'Fluida Statis dan Dinamis',
        description: 'Sifat fluida dan hukum-hukumnya',
        content: 'Konten tentang fluida...',
        category: 'Fisika',
        subject: 'Fluida',
        duration: 65,
        difficulty: 'Menengah',
        tags: ['Fluida', 'Tekanan', 'Bernoulli'],
        publishedDate: new Date('2023-09-22'),
        author: 'Prof. Joko, M.Si.',
        views: 912,
        likes: 64,
        isBookmarked: true,
    },
    {
        id: 'fis-9',
        title: 'Getaran Harmonis',
        description: 'Gerak harmonik sederhana dan pendulum',
        content: 'Konten tentang getaran harmonik...',
        category: 'Fisika',
        subject: 'Getaran',
        duration: 55,
        difficulty: 'Menengah',
        tags: ['Getaran', 'Harmonik', 'Pendulum'],
        publishedDate: new Date('2023-09-20'),
        author: 'Dr. Ani Lestari, M.Pd.',
        views: 845,
        likes: 59,
        isBookmarked: false,
    },

    {
        id: 'kim-1',
        title: 'Struktur Atom dan Sistem Periodik',
        description: 'Mempelajari perkembangan teori atom dan pengelompokan unsur dalam sistem periodik',
        content: `
# Struktur Atom dan Sistem Periodik

## Perkembangan Teori Atom
1. Teori Atom Dalton
2. Teori Atom Thomson
3. Teori Atom Rutherford
4. Teori Atom Bohr
5. Teori Atom Modern

## Sistem Periodik Unsur
Sistem periodik mengelompokkan unsur berdasarkan:
- Nomor atom
- Sifat periodik
- Konfigurasi elektron

## Sifat Periodik
1. Jari-jari atom
2. Energi ionisasi
3. Afinitas elektron
4. Keelektronegatifan
    `,
        category: 'Kimia',
        subject: 'Struktur Atom',
        duration: 50,
        difficulty: 'Pemula',
        tags: ['Atom', 'Sistem Periodik', 'Unsur', 'Kimia Dasar'],
        publishedDate: new Date('2023-10-05'),
        author: 'Cici Novitasari, S.Si.',
        views: 1567,
        likes: 98,
        isBookmarked: true,
    },
    {
        id: 'kim-2',
        title: 'Ikatan Kimia',
        description: 'Jenis-jenis ikatan kimia dan sifatnya',
        content: 'Konten tentang ikatan kimia...',
        category: 'Kimia',
        subject: 'Ikatan Kimia',
        duration: 60,
        difficulty: 'Menengah',
        tags: ['Ionik', 'Kovalen', 'Logam'],
        publishedDate: new Date('2023-10-03'),
        author: 'Dr. Rudi, M.Si.',
        views: 1123,
        likes: 76,
        isBookmarked: false,
    },
    {
        id: 'kim-3',
        title: 'Stoikiometri',
        description: 'Perhitungan kimia berdasarkan hukum dasar',
        content: 'Konten tentang stoikiometri...',
        category: 'Kimia',
        subject: 'Stoikiometri',
        duration: 70,
        difficulty: 'Menengah',
        tags: ['Mol', 'Reaksi', 'Koefisien'],
        publishedDate: new Date('2023-10-01'),
        author: 'Cici Novitasari, S.Si.',
        views: 987,
        likes: 65,
        isBookmarked: true,
    },
    {
        id: 'kim-4',
        title: 'Termokimia',
        description: 'Perubahan energi dalam reaksi kimia',
        content: 'Konten tentang termokimia...',
        category: 'Kimia',
        subject: 'Termokimia',
        duration: 65,
        difficulty: 'Lanjutan',
        tags: ['Entalpi', 'Kalor', 'Reaksi'],
        publishedDate: new Date('2023-09-28'),
        author: 'Dr. Rudi, M.Si.',
        views: 856,
        likes: 58,
        isBookmarked: false,
    },
    {
        id: 'kim-5',
        title: 'Larutan dan Konsentrasi',
        description: 'Jenis larutan dan cara menghitung konsentrasi',
        content: 'Konten tentang larutan...',
        category: 'Kimia',
        subject: 'Larutan',
        duration: 55,
        difficulty: 'Pemula',
        tags: ['Larutan', 'Konsentrasi', 'Molaritas'],
        publishedDate: new Date('2023-09-25'),
        author: 'Cici Novitasari, S.Si.',
        views: 1023,
        likes: 81,
        isBookmarked: true,
    },
    {
        id: 'kim-6',
        title: 'Kimia Organik Dasar',
        description: 'Pengenalan senyawa karbon dan gugus fungsi',
        content: 'Konten tentang kimia organik...',
        category: 'Kimia',
        subject: 'Kimia Organik',
        duration: 75,
        difficulty: 'Menengah',
        tags: ['Karbon', 'Hidrokarbon', 'Gugus Fungsi'],
        publishedDate: new Date('2023-09-22'),
        author: 'Dr. Rudi, M.Si.',
        views: 912,
        likes: 67,
        isBookmarked: false,
    },
    {
        id: 'kim-7',
        title: 'Laju Reaksi',
        description: 'Faktor-faktor yang mempengaruhi kecepatan reaksi',
        content: 'Konten tentang laju reaksi...',
        category: 'Kimia',
        subject: 'Kinetika',
        duration: 60,
        difficulty: 'Menengah',
        tags: ['Laju', 'Katalis', 'Temperatur'],
        publishedDate: new Date('2023-09-20'),
        author: 'Cici Novitasari, S.Si.',
        views: 789,
        likes: 54,
        isBookmarked: true,
    },

    {
        id: 'bio-1',
        title: 'Sel Hewan dan Sel Tumbuhan: Perbedaan dan Persamaan',
        description: 'Analisis komparatif struktur dan fungsi sel hewan serta tumbuhan',
        content: `
# Perbandingan Sel Hewan dan Tumbuhan

## Persamaan
1. Memiliki membran sel
2. Memiliki sitoplasma
3. Memiliki inti sel (nukleus)
4. Memiliki organel sel seperti mitokondria, retikulum endoplasma, dan badan golgi

## Perbedaan
### Sel Hewan
- Tidak memiliki dinding sel
- Tidak memiliki plastida
- Memiliki sentriol
- Vakuola kecil atau tidak ada

### Sel Tumbuhan
- Memiliki dinding sel dari selulosa
- Memiliki plastida (kloroplas, kromoplas, leukoplas)
- Tidak memiliki sentriol
- Memiliki vakuola besar
    `,
        category: 'Biologi',
        subject: 'Sel',
        duration: 40,
        difficulty: 'Pemula',
        tags: ['Sel', 'Hewan', 'Tumbuhan', 'Biologi Sel'],
        publishedDate: new Date('2023-10-01'),
        author: 'Dr. Deni Setiawan, M.Si.',
        views: 2134,
        likes: 156,
        isBookmarked: false,
    },
    {
        id: 'bio-2',
        title: 'Sistem Pencernaan Manusia',
        description: 'Organ-organ pencernaan dan fungsinya',
        content: 'Konten tentang sistem pencernaan...',
        category: 'Biologi',
        subject: 'Anatomi',
        duration: 55,
        difficulty: 'Menengah',
        tags: ['Pencernaan', 'Enzim', 'Nutrisi'],
        publishedDate: new Date('2023-09-28'),
        author: 'Siti Rahayu, S.Si.',
        views: 1345,
        likes: 98,
        isBookmarked: true,
    },
    {
        id: 'bio-3',
        title: 'Genetika dan DNA',
        description: 'Struktur DNA dan pewarisan sifat',
        content: 'Konten tentang genetika...',
        category: 'Biologi',
        subject: 'Genetika',
        duration: 70,
        difficulty: 'Lanjutan',
        tags: ['DNA', 'Gen', 'Kromosom'],
        publishedDate: new Date('2023-09-25'),
        author: 'Dr. Deni Setiawan, M.Si.',
        views: 1567,
        likes: 112,
        isBookmarked: false,
    },
    {
        id: 'bio-4',
        title: 'Ekosistem dan Interaksi',
        description: 'Komponen ekosistem dan rantai makanan',
        content: 'Konten tentang ekosistem...',
        category: 'Biologi',
        subject: 'Ekologi',
        duration: 50,
        difficulty: 'Pemula',
        tags: ['Ekosistem', 'Rantai Makanan', 'Bioma'],
        publishedDate: new Date('2023-09-22'),
        author: 'Siti Rahayu, S.Si.',
        views: 1123,
        likes: 87,
        isBookmarked: true,
    },
    {
        id: 'bio-5',
        title: 'Sistem Pernapasan',
        description: 'Mekanisme pernapasan pada manusia',
        content: 'Konten tentang sistem pernapasan...',
        category: 'Biologi',
        subject: 'Anatomi',
        duration: 45,
        difficulty: 'Pemula',
        tags: ['Pernapasan', 'Paru-paru', 'Oksigen'],
        publishedDate: new Date('2023-09-20'),
        author: 'Dr. Deni Setiawan, M.Si.',
        views: 987,
        likes: 65,
        isBookmarked: false,
    },
    {
        id: 'bio-6',
        title: 'Evolusi dan Seleksi Alam',
        description: 'Teori evolusi dan mekanisme seleksi alam',
        content: 'Konten tentang evolusi...',
        category: 'Biologi',
        subject: 'Evolusi',
        duration: 65,
        difficulty: 'Lanjutan',
        tags: ['Evolusi', 'Darwin', 'Seleksi Alam'],
        publishedDate: new Date('2023-09-18'),
        author: 'Siti Rahayu, S.Si.',
        views: 856,
        likes: 73,
        isBookmarked: true,
    },
    {
        id: 'bio-7',
        title: 'Sistem Saraf',
        description: 'Struktur dan fungsi sistem saraf manusia',
        content: 'Konten tentang sistem saraf...',
        category: 'Biologi',
        subject: 'Anatomi',
        duration: 60,
        difficulty: 'Menengah',
        tags: ['Saraf', 'Neuron', 'Otak'],
        publishedDate: new Date('2023-09-15'),
        author: 'Dr. Deni Setiawan, M.Si.',
        views: 1023,
        likes: 81,
        isBookmarked: false,
    },
    {
        id: 'bio-8',
        title: 'Kingdom Plantae',
        description: 'Klasifikasi tumbuhan dan ciri-cirinya',
        content: 'Konten tentang plantae...',
        category: 'Biologi',
        subject: 'Taksonomi',
        duration: 55,
        difficulty: 'Menengah',
        tags: ['Tumbuhan', 'Klasifikasi', 'Fotosintesis'],
        publishedDate: new Date('2023-09-12'),
        author: 'Siti Rahayu, S.Si.',
        views: 789,
        likes: 54,
        isBookmarked: true,
    },
    {
        id: 'bio-9',
        title: 'Bioteknologi Modern',
        description: 'Aplikasi bioteknologi dalam kehidupan',
        content: 'Konten tentang bioteknologi...',
        category: 'Biologi',
        subject: 'Bioteknologi',
        duration: 70,
        difficulty: 'Lanjutan',
        tags: ['Rekayasa Genetika', 'Kloning', 'GMO'],
        publishedDate: new Date('2023-09-10'),
        author: 'Dr. Deni Setiawan, M.Si.',
        views: 923,
        likes: 68,
        isBookmarked: false,
    },
    {
        id: 'bio-10',
        title: 'Sistem Ekskresi',
        description: 'Organ-organ ekskresi dan fungsinya',
        content: 'Konten tentang sistem ekskresi...',
        category: 'Biologi',
        subject: 'Anatomi',
        duration: 50,
        difficulty: 'Pemula',
        tags: ['Ekskresi', 'Ginjal', 'Kulit'],
        publishedDate: new Date('2023-09-08'),
        author: 'Siti Rahayu, S.Si.',
        views: 845,
        likes: 59,
        isBookmarked: true,
    },

    {
        id: 'ind-1',
        title: 'Pembahasan Soal UN Bahasa Indonesia 2023',
        description: 'Analisis mendalam soal UN Bahasa Indonesia dengan strategi penyelesaian',
        content: `
# Pembahasan Soal UN Bahasa Indonesia 2023

## Bagian Membaca
Teknik membaca cepat dan menemukan ide pokok.

## Bagian Menulis
Struktur paragraf yang baik:
1. Kalimat utama
2. Kalimat penjelas
3. Kalimat penutup

## Contoh Soal dan Pembahasan
**Soal:** Manakah kalimat yang menggunakan ejaan yang benar?
A. Di-mana kamu tinggal?
B. Dimana kamu tinggal?
C. Di mana kamu tinggal?
D. Dimana kamu tinggal?

**Jawaban:** C. Di mana kamu tinggal

**Alasan:** "Di mana" ditulis terpisah karena menunjukkan tempat.
    `,
        category: 'Bahasa Indonesia',
        subject: 'Ujian Nasional',
        duration: 55,
        difficulty: 'Menengah',
        tags: ['UN', 'Bahasa Indonesia', 'Soal', 'Pembahasan'],
        publishedDate: new Date('2023-09-28'),
        author: 'Eka Putri, S.Pd.',
        views: 1890,
        likes: 112,
        isBookmarked: true,
    },
    {
        id: 'ind-2',
        title: 'Teks Prosedur',
        description: 'Struktur dan ciri kebahasaan teks prosedur',
        content: 'Konten tentang teks prosedur...',
        category: 'Bahasa Indonesia',
        subject: 'Teks',
        duration: 40,
        difficulty: 'Pemula',
        tags: ['Prosedur', 'Langkah', 'Instruksi'],
        publishedDate: new Date('2023-09-25'),
        author: 'Ahmad Fauzi, M.Pd.',
        views: 1123,
        likes: 76,
        isBookmarked: false,
    },
    {
        id: 'ind-3',
        title: 'Puisi dan Majas',
        description: 'Analisis unsur intrinsik puisi',
        content: 'Konten tentang puisi...',
        category: 'Bahasa Indonesia',
        subject: 'Sastra',
        duration: 50,
        difficulty: 'Menengah',
        tags: ['Puisi', 'Majas', 'Rima'],
        publishedDate: new Date('2023-09-22'),
        author: 'Eka Putri, S.Pd.',
        views: 987,
        likes: 65,
        isBookmarked: true,
    },
    {
        id: 'ind-4',
        title: 'Ejaan yang Disempurnakan (EYD)',
        description: 'Panduan penggunaan EYD terbaru',
        content: 'Konten tentang EYD...',
        category: 'Bahasa Indonesia',
        subject: 'Ejaan',
        duration: 45,
        difficulty: 'Pemula',
        tags: ['EYD', 'Ejaan', 'Tanda Baca'],
        publishedDate: new Date('2023-09-20'),
        author: 'Ahmad Fauzi, M.Pd.',
        views: 1345,
        likes: 89,
        isBookmarked: false,
    },
    {
        id: 'ind-5',
        title: 'Teks Eksposisi',
        description: 'Ciri dan struktur teks eksposisi',
        content: 'Konten tentang teks eksposisi...',
        category: 'Bahasa Indonesia',
        subject: 'Teks',
        duration: 55,
        difficulty: 'Menengah',
        tags: ['Eksposisi', 'Argumentasi', 'Fakta'],
        publishedDate: new Date('2023-09-18'),
        author: 'Eka Putri, S.Pd.',
        views: 856,
        likes: 58,
        isBookmarked: true,
    },
    {
        id: 'ind-6',
        title: 'Cerpen dan Unsur Instrinsik',
        description: 'Analisis cerita pendek',
        content: 'Konten tentang cerpen...',
        category: 'Bahasa Indonesia',
        subject: 'Sastra',
        duration: 60,
        difficulty: 'Menengah',
        tags: ['Cerpen', 'Tokoh', 'Alur'],
        publishedDate: new Date('2023-09-15'),
        author: 'Ahmad Fauzi, M.Pd.',
        views: 1023,
        likes: 81,
        isBookmarked: false,
    },
    {
        id: 'ind-7',
        title: 'Kalimat Efektif',
        description: 'Ciri-ciri kalimat efektif dan contohnya',
        content: 'Konten tentang kalimat efektif...',
        category: 'Bahasa Indonesia',
        subject: 'Tata Bahasa',
        duration: 40,
        difficulty: 'Pemula',
        tags: ['Kalimat', 'Efektif', 'Struktur'],
        publishedDate: new Date('2023-09-12'),
        author: 'Eka Putri, S.Pd.',
        views: 789,
        likes: 54,
        isBookmarked: true,
    },
    {
        id: 'ind-8',
        title: 'Teks Laporan Hasil Observasi',
        description: 'Struktur dan contoh teks LHO',
        content: 'Konten tentang teks LHO...',
        category: 'Bahasa Indonesia',
        subject: 'Teks',
        duration: 50,
        difficulty: 'Menengah',
        tags: ['LHO', 'Observasi', 'Laporan'],
        publishedDate: new Date('2023-09-10'),
        author: 'Ahmad Fauzi, M.Pd.',
        views: 912,
        likes: 67,
        isBookmarked: false,
    },
    {
        id: 'ind-9',
        title: 'Novel dan Analisisnya',
        description: 'Unsur intrinsik dan ekstrinsik novel',
        content: 'Konten tentang novel...',
        category: 'Bahasa Indonesia',
        subject: 'Sastra',
        duration: 70,
        difficulty: 'Lanjutan',
        tags: ['Novel', 'Karakter', 'Setting'],
        publishedDate: new Date('2023-09-08'),
        author: 'Eka Putri, S.Pd.',
        views: 734,
        likes: 49,
        isBookmarked: true,
    },
    {
        id: 'ind-10',
        title: 'Debat dan Argumentasi',
        description: 'Teknik berdebat yang baik',
        content: 'Konten tentang debat...',
        category: 'Bahasa Indonesia',
        subject: 'Berbicara',
        duration: 60,
        difficulty: 'Lanjutan',
        tags: ['Debat', 'Argumentasi', 'Logika'],
        publishedDate: new Date('2023-09-05'),
        author: 'Ahmad Fauzi, M.Pd.',
        views: 845,
        likes: 62,
        isBookmarked: false,
    },
    {
        id: 'ind-11',
        title: 'Surat Resmi',
        description: 'Format dan bahasa surat resmi',
        content: 'Konten tentang surat resmi...',
        category: 'Bahasa Indonesia',
        subject: 'Menulis',
        duration: 45,
        difficulty: 'Pemula',
        tags: ['Surat', 'Resmi', 'Format'],
        publishedDate: new Date('2023-09-03'),
        author: 'Eka Putri, S.Pd.',
        views: 923,
        likes: 71,
        isBookmarked: true,
    },

    {
        id: 'ing-1',
        title: 'English Tenses Mastery for Final Exam',
        description: 'Complete guide to mastering all English tenses with practical examples',
        content: `
# English Tenses Mastery

## Simple Present Tense
Digunakan untuk kebiasaan, fakta umum, dan jadwal.

## Present Continuous Tense
Digunakan untuk aktivitas yang sedang berlangsung sekarang.

## Simple Past Tense
Digunakan untuk aktivitas yang selesai di waktu lampau.

## Past Continuous Tense
Digunakan untuk aktivitas yang sedang berlangsung di waktu lampau.

## Future Tenses
1. Simple Future (will + V1)
2. Be going to
3. Future Continuous
4. Future Perfect

## Tips Menguasai Tenses
1. Pahami konteks waktu
2. Hafal pola kalimat
3. Banyak latihan soal
    `,
        category: 'Bahasa Inggris',
        subject: 'Grammar',
        duration: 70,
        difficulty: 'Lanjutan',
        tags: ['Tenses', 'Grammar', 'English', 'Tata Bahasa'],
        publishedDate: new Date('2023-09-25'),
        author: 'Fajar Nugroho, S.Pd.',
        views: 2456,
        likes: 187,
        isBookmarked: false,
    },
    {
        id: 'ing-2',
        title: 'Reading Comprehension Strategies',
        description: 'Teknik memahami teks bahasa Inggris dengan cepat',
        content: 'Konten tentang reading comprehension...',
        category: 'Bahasa Inggris',
        subject: 'Reading',
        duration: 50,
        difficulty: 'Menengah',
        tags: ['Reading', 'Comprehension', 'Strategi'],
        publishedDate: new Date('2023-09-22'),
        author: 'Lisa Wijaya, S.Pd.',
        views: 1567,
        likes: 98,
        isBookmarked: true,
    },
    {
        id: 'ing-3',
        title: 'Writing Essay for TOEFL',
        description: 'Struktur esai bahasa Inggris yang baik',
        content: 'Konten tentang writing essay...',
        category: 'Bahasa Inggris',
        subject: 'Writing',
        duration: 80,
        difficulty: 'Lanjutan',
        tags: ['Writing', 'Essay', 'TOEFL'],
        publishedDate: new Date('2023-09-20'),
        author: 'Fajar Nugroho, S.Pd.',
        views: 1345,
        likes: 112,
        isBookmarked: false,
    },
    {
        id: 'ing-4',
        title: 'Vocabulary Building',
        description: 'Cara memperkaya kosakata bahasa Inggris',
        content: 'Konten tentang vocabulary...',
        category: 'Bahasa Inggris',
        subject: 'Vocabulary',
        duration: 45,
        difficulty: 'Pemula',
        tags: ['Vocabulary', 'Kosakata', 'Hafalan'],
        publishedDate: new Date('2023-09-18'),
        author: 'Lisa Wijaya, S.Pd.',
        views: 1890,
        likes: 134,
        isBookmarked: true,
    },
    {
        id: 'ing-5',
        title: 'Listening Practice for IELTS',
        description: 'Latihan mendengarkan untuk persiapan IELTS',
        content: 'Konten tentang listening...',
        category: 'Bahasa Inggris',
        subject: 'Listening',
        duration: 60,
        difficulty: 'Menengah',
        tags: ['Listening', 'IELTS', 'Practice'],
        publishedDate: new Date('2023-09-15'),
        author: 'Fajar Nugroho, S.Pd.',
        views: 1123,
        likes: 89,
        isBookmarked: false,
    },
    {
        id: 'ing-6',
        title: 'Speaking with Confidence',
        description: 'Teknik berbicara bahasa Inggris dengan percaya diri',
        content: 'Konten tentang speaking...',
        category: 'Bahasa Inggris',
        subject: 'Speaking',
        duration: 55,
        difficulty: 'Menengah',
        tags: ['Speaking', 'Percaya Diri', 'Pronunciation'],
        publishedDate: new Date('2023-09-12'),
        author: 'Lisa Wijaya, S.Pd.',
        views: 1456,
        likes: 103,
        isBookmarked: true,
    },

    {
        id: 'sej-1',
        title: 'Perang Dunia II: Sebab dan Akibat',
        description: 'Analisis penyebab dan dampak Perang Dunia II',
        content: 'Konten tentang Perang Dunia II...',
        category: 'Sejarah',
        subject: 'Sejarah Dunia',
        duration: 65,
        difficulty: 'Menengah',
        tags: ['Perang Dunia', 'Global', 'Konflik'],
        publishedDate: new Date('2023-10-08'),
        author: 'Prof. Hadi, M.Hum.',
        views: 1345,
        likes: 98,
        isBookmarked: true,
    },
    {
        id: 'sej-2',
        title: 'Kerajaan Majapahit',
        description: 'Kejayaan dan keruntuhan Majapahit',
        content: 'Konten tentang Majapahit...',
        category: 'Sejarah',
        subject: 'Sejarah Indonesia',
        duration: 55,
        difficulty: 'Pemula',
        tags: ['Majapahit', 'Gajah Mada', 'Nusantara'],
        publishedDate: new Date('2023-10-05'),
        author: 'Dr. Siti, M.Pd.',
        views: 1123,
        likes: 87,
        isBookmarked: false,
    },
    {
        id: 'sej-3',
        title: 'Revolusi Industri 4.0',
        description: 'Dampak revolusi industri terhadap masyarakat',
        content: 'Konten tentang revolusi industri...',
        category: 'Sejarah',
        subject: 'Sejarah Ekonomi',
        duration: 70,
        difficulty: 'Lanjutan',
        tags: ['Industri', 'Teknologi', 'Digital'],
        publishedDate: new Date('2023-10-03'),
        author: 'Prof. Hadi, M.Hum.',
        views: 987,
        likes: 65,
        isBookmarked: true,
    },
    {
        id: 'sej-4',
        title: 'Kolonialisme di Indonesia',
        description: 'Pengaruh kolonialisme Belanda dan Jepang',
        content: 'Konten tentang kolonialisme...',
        category: 'Sejarah',
        subject: 'Sejarah Indonesia',
        duration: 60,
        difficulty: 'Menengah',
        tags: ['Kolonial', 'Penjajahan', 'Kemerdekaan'],
        publishedDate: new Date('2023-10-01'),
        author: 'Dr. Siti, M.Pd.',
        views: 1345,
        likes: 92,
        isBookmarked: false,
    },
    {
        id: 'sej-5',
        title: 'Peradaban Mesir Kuno',
        description: 'Kehidupan dan pencapaian Mesir Kuno',
        content: 'Konten tentang Mesir Kuno...',
        category: 'Sejarah',
        subject: 'Sejarah Dunia',
        duration: 50,
        difficulty: 'Pemula',
        tags: ['Mesir', 'Piramida', 'Firaun'],
        publishedDate: new Date('2023-09-28'),
        author: 'Prof. Hadi, M.Hum.',
        views: 856,
        likes: 73,
        isBookmarked: true,
    },
    {
        id: 'sej-6',
        title: 'Sejarah Islam di Nusantara',
        description: 'Penyebaran dan perkembangan Islam di Indonesia',
        content: 'Konten tentang Islam Nusantara...',
        category: 'Sejarah',
        subject: 'Sejarah Agama',
        duration: 55,
        difficulty: 'Menengah',
        tags: ['Islam', 'Wali Songo', 'Pesantren'],
        publishedDate: new Date('2023-09-25'),
        author: 'Dr. Siti, M.Pd.',
        views: 1023,
        likes: 81,
        isBookmarked: false,
    },

    {
        id: 'geo-1',
        title: 'Litosfer dan Batuan',
        description: 'Struktur litosfer dan jenis-jenis batuan',
        content: 'Konten tentang litosfer...',
        category: 'Geografi',
        subject: 'Geologi',
        duration: 50,
        difficulty: 'Pemula',
        tags: ['Litosfer', 'Batuan', 'Mineral'],
        publishedDate: new Date('2023-10-10'),
        author: 'Dr. Arif, M.Si.',
        views: 1123,
        likes: 76,
        isBookmarked: true,
    },
    {
        id: 'geo-2',
        title: 'Cuaca dan Iklim',
        description: 'Perbedaan cuaca dan iklim serta faktornya',
        content: 'Konten tentang cuaca dan iklim...',
        category: 'Geografi',
        subject: 'Klimatologi',
        duration: 60,
        difficulty: 'Menengah',
        tags: ['Cuaca', 'Iklim', 'Monsun'],
        publishedDate: new Date('2023-10-08'),
        author: 'Maya Sari, S.Pd.',
        views: 1345,
        likes: 98,
        isBookmarked: false,
    },
    {
        id: 'geo-3',
        title: 'Peta dan Pemetaan',
        description: 'Jenis peta dan teknik pembuatannya',
        content: 'Konten tentang peta...',
        category: 'Geografi',
        subject: 'Kartografi',
        duration: 55,
        difficulty: 'Pemula',
        tags: ['Peta', 'Skala', 'Proyeksi'],
        publishedDate: new Date('2023-10-05'),
        author: 'Dr. Arif, M.Si.',
        views: 987,
        likes: 65,
        isBookmarked: true,
    },
    {
        id: 'geo-4',
        title: 'Biosfer dan Persebaran Flora Fauna',
        description: 'Zona biosfer dan keanekaragaman hayati',
        content: 'Konten tentang biosfer...',
        category: 'Geografi',
        subject: 'Biogeografi',
        duration: 65,
        difficulty: 'Menengah',
        tags: ['Biosfer', 'Flora', 'Fauna'],
        publishedDate: new Date('2023-10-03'),
        author: 'Maya Sari, S.Pd.',
        views: 1123,
        likes: 81,
        isBookmarked: false,
    },
    {
        id: 'geo-5',
        title: 'Urbanisasi dan Permukiman',
        description: 'Dampak urbanisasi terhadap permukiman',
        content: 'Konten tentang urbanisasi...',
        category: 'Geografi',
        subject: 'Geografi Manusia',
        duration: 70,
        difficulty: 'Lanjutan',
        tags: ['Urbanisasi', 'Kota', 'Desa'],
        publishedDate: new Date('2023-10-01'),
        author: 'Dr. Arif, M.Si.',
        views: 856,
        likes: 58,
        isBookmarked: true,
    },
    {
        id: 'geo-6',
        title: 'Bencana Alam dan Mitigasi',
        description: 'Jenis bencana alam dan upaya pencegahannya',
        content: 'Konten tentang bencana alam...',
        category: 'Geografi',
        subject: 'Geografi Bencana',
        duration: 60,
        difficulty: 'Menengah',
        tags: ['Bencana', 'Gempa', 'Mitigasi'],
        publishedDate: new Date('2023-09-28'),
        author: 'Maya Sari, S.Pd.',
        views: 1456,
        likes: 103,
        isBookmarked: false,
    },
    {
        id: 'geo-7',
        title: 'Sumber Daya Alam',
        description: 'Pengelolaan sumber daya alam berkelanjutan',
        content: 'Konten tentang SDA...',
        category: 'Geografi',
        subject: 'SDA',
        duration: 55,
        difficulty: 'Menengah',
        tags: ['SDA', 'Energi', 'Berkelanjutan'],
        publishedDate: new Date('2023-09-25'),
        author: 'Dr. Arif, M.Si.',
        views: 1023,
        likes: 76,
        isBookmarked: true,
    },
    {
        id: 'geo-8',
        title: 'Atmosfer dan Lapisannya',
        description: 'Struktur atmosfer dan fungsinya',
        content: 'Konten tentang atmosfer...',
        category: 'Geografi',
        subject: 'Meteorologi',
        duration: 50,
        difficulty: 'Pemula',
        tags: ['Atmosfer', 'Ozon', 'UV'],
        publishedDate: new Date('2023-09-22'),
        author: 'Maya Sari, S.Pd.',
        views: 789,
        likes: 54,
        isBookmarked: false,
    },
    {
        id: 'geo-9',
        title: 'Geografi Pariwisata',
        description: 'Potensi wisata dan pengembangannya',
        content: 'Konten tentang pariwisata...',
        category: 'Geografi',
        subject: 'Geografi Pariwisata',
        duration: 65,
        difficulty: 'Menengah',
        tags: ['Pariwisata', 'Destinasi', 'Ekowisata'],
        publishedDate: new Date('2023-09-20'),
        author: 'Dr. Arif, M.Si.',
        views: 923,
        likes: 68,
        isBookmarked: true,
    },
    {
        id: 'geo-10',
        title: 'Hidrosfer dan Siklus Air',
        description: 'Komponen hidrosfer dan siklus hidrologi',
        content: 'Konten tentang hidrosfer...',
        category: 'Geografi',
        subject: 'Hidrologi',
        duration: 55,
        difficulty: 'Pemula',
        tags: ['Hidrosfer', 'Air', 'Siklus'],
        publishedDate: new Date('2023-09-18'),
        author: 'Maya Sari, S.Pd.',
        views: 845,
        likes: 62,
        isBookmarked: false,
    },
    {
        id: 'geo-11',
        title: 'Globalisasi dan Dampaknya',
        description: 'Pengaruh globalisasi pada geografi',
        content: 'Konten tentang globalisasi...',
        category: 'Geografi',
        subject: 'Geografi Ekonomi',
        duration: 70,
        difficulty: 'Lanjutan',
        tags: ['Globalisasi', 'Ekonomi', 'Budaya'],
        publishedDate: new Date('2023-09-15'),
        author: 'Dr. Arif, M.Si.',
        views: 1123,
        likes: 87,
        isBookmarked: true,
    },
    {
        id: 'geo-12',
        title: 'Penginderaan Jauh',
        description: 'Teknologi penginderaan jauh dalam geografi',
        content: 'Konten tentang penginderaan jauh...',
        category: 'Geografi',
        subject: 'Remote Sensing',
        duration: 75,
        difficulty: 'Lanjutan',
        tags: ['Remote Sensing', 'GIS', 'Satelit'],
        publishedDate: new Date('2023-09-12'),
        author: 'Maya Sari, S.Pd.',
        views: 734,
        likes: 49,
        isBookmarked: false,
    },
];